= Open Liberty Operator Labs

Welcome to the Open Liberty Operator Labs. This series of labs is designed to help you explore and learn about the advanced features of Open Liberty Operator on Red Hat® OpenShift® Container Platform.

During the lab sessions, you will have the opportunity to explore the following features:

* link:++1-AutoscalingLab++[1. Horizontal Pod Autoscaling with CPU and Memory resource constraints]
* link:++2-KnativeLab++[2. Knative services]
* link:++3-CertManagerLab++[3. Certificate management and TLS]
* link:++4-SemeruLab++[4. Semeru Cloud Compiler (JIT Server integration)]

== Open Liberty Operator
If you are interested in gaining in-depth knowledge about Open Liberty Operator, refer to the link:++https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1.adoc++[documentation].

== Lab Prerequisites
Before starting the lab, please ensure you meet the following requirements:

1. The `oc` client installed on your system. If you do not have it installed, follow the steps:
** Download the client through the link:++https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.12/++[link]:
*** Intel Mac: openshift-client-mac.tar.gz
*** M1/M2 Mac: openshift-client-mac-arm64.tar.gz
*** Windows: openshift-client-windows.zip
*** Linux: openshift-client-linux.tar.gz
** Unzip the file. Add the directory where `oc` is extracted to your _PATH_:
*** Mac/Linux:
+
[source,sh]
----
export PATH=$OC_HOME:$PATH
----
+
**** For example:
+
[source,sh]
----
export PATH=${HOME}/Downloads/openshift-client-mac/:$PATH
----
+

*** Windows Command Prompt:
+
[source,sh]
----
set PATH=$OC_HOME;%PATH%
----
+
**** For example:
+
[source,sh]
----
set PATH=%HOMEPATH%\Downloads\openshift-client-windows\;%PATH%
----

*** Windows Cygwin Terminal:
+
[source,sh]
----
export PATH=$OC_HOME:$PATH
----
+
**** For example:
+
[source,sh]
----
export PATH=${HOMEPATH}/Downloads/openshift-client-windows/:$PATH
----

2. Access to an OpenShift cluster with Open Liberty Operator already installed.
+
[source,sh]
----
oc login <CLUSTER_URL> -u <CLUSTER_USER> -p <CLUSTER_TOKEN> --insecure-skip-tls-verify=true
export NAMESPACE=<ASSIGNED_NAMESPACE>
oc project $NAMESPACE
----
** CLUSTER_URL, CLUSTER_USER, CLUSTER_TOKEN and ASSIGNED_NAMESPACE will be provided to you before the lab. If you do not have access, please contact the Lab Administrator to obtain the necessary permissions.
3. Ensure `jq` is installed.
** Download and install the binary through the link:++https://jqlang.github.io/jq/download/++[link].

== Kubernetes Basics
If you are new to containers and Kubernetes, see below to learn the basics.

=== Containers and Docker
Review the link:++https://www.ibm.com/cloud/architecture/content/course/containers-and-docker++[one hour course for an introduction to containers and docker].

=== Kubernetes Fundamentals
Review the link:++https://www.ibm.com/cloud/architecture/content/course/kubernetes-101++[one hour course for an introduction to Kubernetes].
