= Horizontal Pod Autoscaler Configuration

This lab focuses on the configuration of Horizontal Pod Autoscaling for OpenLibertyApplication instances.

== Horizontal Pod Autoscaling
`HorizontalPodAutoscaler` automatically scales a workload resource to based on the configured demand, such as CPU and memory consumption. Horizontal scaling involves adjusting the number of Pods to handle the load. For example, if the load decreases and the number of running Pods is above the minimum configuration, the number of Pods will scale down. The same principle applies in the opposite scenario.

==== Configuration Options
There are two methods to deploy OpenLibertyApplication instance on your cluster.

=== Option A: Through `oc` client

1. Set your current namespace using the command: `oc project $NAMESPACE`

2. Create a YAML file called `liberty-autoscaling.yaml` with the following content
+
[source,yaml]
----
apiVersion: apps.openliberty.io/v1
kind: OpenLibertyApplication
metadata:
  name: autoscaling-liberty-app
spec:
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started
  replicas: 1
  expose: false
  probes:
    readiness:
      httpGet:
        path: /
        port: 9080
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 24
    liveness:
      httpGet:
        path: /
        port: 9080
      initialDelaySeconds: 8
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 12
----

3. Create the OpenLibertyApplication instance using the command: `oc apply -f liberty-autoscaling.yaml`. This will create a Deployment named `autoscaling-liberty-app` with 1 replica.

4. Edit the OpenLibertyApplication instance to use `autoscaling` field as opposed to `replicas` field. Run the command: `oc edit OpenLibertyApplication autoscaling-liberty-app`. Remove `replicas: 1` under `spec` and replace it with the following:
+
[source,yaml]
----
spec:
  resources:
    requests:
      cpu: "0.4"
  autoscaling:
    maxReplicas: 5
    minReplicas: 3
    targetCPUUtilizationPercentage: 50
----
`resources` field defines a metrice source for targeted container resources. In this example, it  `autoscaling` field configures the range of number of Pods for a workload using `maxReplicas` and `minReplicas`. These fields ensure that the number of Pods falls within the specified range.

=== Option B: Through OpenShift Web Console
